### ISSUE TITLE
informational entry for Doors2Dim

### ISSUE THREAD

**Issue by macarena-sagredo** [esrlabs/dox#42]
A dim file should contain the following characteristics:

- 
- origin
- 
- version
- 
- date of exchange
- 
- baseline (if applicable)
- 
- etc…

This can be achieved by e.g. adding an information-entry during Doors2Dim:

```
module: moduleName

ModuleName_MetaInfo:
  type: information
  text: |
        origin: ...
        version: ...
        date: ...
        
```

The process should also describe how internal dim files are handled, for example, when the characteristics do not apply and git SHA-1 suffices.
